// Code generated by protoc-gen-go. DO NOT EDIT.
// source: feed.proto

/*
Package feed is a generated protocol buffer package.

It is generated from these files:
	feed.proto

It has these top-level messages:
	FeedResponse
*/
package feed

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "go.pedge.io/pb/go/google/protobuf"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type FeedResponse struct {
	Message string `protobuf:"bytes,1,opt,name=message" json:"message,omitempty"`
}

func (m *FeedResponse) Reset()                    { *m = FeedResponse{} }
func (m *FeedResponse) String() string            { return proto.CompactTextString(m) }
func (*FeedResponse) ProtoMessage()               {}
func (*FeedResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *FeedResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*FeedResponse)(nil), "feed.FeedResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Feeder service

type FeederClient interface {
	GetNewFeed(ctx context.Context, in *google_protobuf.Empty, opts ...grpc.CallOption) (*FeedResponse, error)
}

type feederClient struct {
	cc *grpc.ClientConn
}

func NewFeederClient(cc *grpc.ClientConn) FeederClient {
	return &feederClient{cc}
}

func (c *feederClient) GetNewFeed(ctx context.Context, in *google_protobuf.Empty, opts ...grpc.CallOption) (*FeedResponse, error) {
	out := new(FeedResponse)
	err := grpc.Invoke(ctx, "/feed.Feeder/GetNewFeed", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Feeder service

type FeederServer interface {
	GetNewFeed(context.Context, *google_protobuf.Empty) (*FeedResponse, error)
}

func RegisterFeederServer(s *grpc.Server, srv FeederServer) {
	s.RegisterService(&_Feeder_serviceDesc, srv)
}

func _Feeder_GetNewFeed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(google_protobuf.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FeederServer).GetNewFeed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/feed.Feeder/GetNewFeed",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FeederServer).GetNewFeed(ctx, req.(*google_protobuf.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _Feeder_serviceDesc = grpc.ServiceDesc{
	ServiceName: "feed.Feeder",
	HandlerType: (*FeederServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetNewFeed",
			Handler:    _Feeder_GetNewFeed_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "feed.proto",
}

func init() { proto.RegisterFile("feed.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 144 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4a, 0x4b, 0x4d, 0x4d,
	0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x01, 0xb1, 0xa5, 0xa4, 0xd3, 0xf3, 0xf3, 0xd3,
	0x73, 0x52, 0xf5, 0xc1, 0x62, 0x49, 0xa5, 0x69, 0xfa, 0xa9, 0xb9, 0x05, 0x25, 0x95, 0x10, 0x25,
	0x4a, 0x1a, 0x5c, 0x3c, 0x6e, 0xa9, 0xa9, 0x29, 0x41, 0xa9, 0xc5, 0x05, 0xf9, 0x79, 0xc5, 0xa9,
	0x42, 0x12, 0x5c, 0xec, 0xb9, 0xa9, 0xc5, 0xc5, 0x89, 0xe9, 0xa9, 0x12, 0x8c, 0x0a, 0x8c, 0x1a,
	0x9c, 0x41, 0x30, 0xae, 0x91, 0x0b, 0x17, 0x1b, 0x48, 0x65, 0x6a, 0x91, 0x90, 0x15, 0x17, 0x97,
	0x7b, 0x6a, 0x89, 0x5f, 0x6a, 0x39, 0x88, 0x2f, 0x24, 0xa6, 0x07, 0x31, 0x5f, 0x0f, 0x66, 0xbe,
	0x9e, 0x2b, 0xc8, 0x7c, 0x29, 0x21, 0x3d, 0xb0, 0x4b, 0x90, 0x4d, 0x57, 0x62, 0x48, 0x62, 0x03,
	0xab, 0x32, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0xa3, 0x2d, 0xa6, 0xff, 0xa7, 0x00, 0x00, 0x00,
}
