FROM golang:1.10-alpine

ARG REPO="github.com/jun06t/grpc-sample/grpc-gateway"

RUN mkdir -p /go/src/${REPO}
COPY . /go/src/${REPO}

WORKDIR /go/src/${REPO}

RUN go build -o main ./gateway/main.go

EXPOSE 3000

CMD ["/go/src/main"]
