// Code generated by protoc-gen-go. DO NOT EDIT.
// source: helloworld.proto

package helloworld

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ErrorCode int32

const (
	ErrorCode_UNKNOWN         ErrorCode = 0
	ErrorCode_INVALID_RECEIPT ErrorCode = 1
	ErrorCode_EXPIRED_RECEIPT ErrorCode = 2
	ErrorCode_INVALID_CARD    ErrorCode = 3
	ErrorCode_EXPIRED_CARD    ErrorCode = 4
	ErrorCode_INVALID_COUNTRY ErrorCode = 5
	ErrorCode_PREPAID_CARD    ErrorCode = 6
)

var ErrorCode_name = map[int32]string{
	0: "UNKNOWN",
	1: "INVALID_RECEIPT",
	2: "EXPIRED_RECEIPT",
	3: "INVALID_CARD",
	4: "EXPIRED_CARD",
	5: "INVALID_COUNTRY",
	6: "PREPAID_CARD",
}

var ErrorCode_value = map[string]int32{
	"UNKNOWN":         0,
	"INVALID_RECEIPT": 1,
	"EXPIRED_RECEIPT": 2,
	"INVALID_CARD":    3,
	"EXPIRED_CARD":    4,
	"INVALID_COUNTRY": 5,
	"PREPAID_CARD":    6,
}

func (x ErrorCode) String() string {
	return proto.EnumName(ErrorCode_name, int32(x))
}

func (ErrorCode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_17b8c58d586b62f2, []int{0}
}

type HelloRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloRequest) Reset()         { *m = HelloRequest{} }
func (m *HelloRequest) String() string { return proto.CompactTextString(m) }
func (*HelloRequest) ProtoMessage()    {}
func (*HelloRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_17b8c58d586b62f2, []int{0}
}

func (m *HelloRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloRequest.Unmarshal(m, b)
}
func (m *HelloRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloRequest.Marshal(b, m, deterministic)
}
func (m *HelloRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloRequest.Merge(m, src)
}
func (m *HelloRequest) XXX_Size() int {
	return xxx_messageInfo_HelloRequest.Size(m)
}
func (m *HelloRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HelloRequest proto.InternalMessageInfo

func (m *HelloRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type HelloReply struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloReply) Reset()         { *m = HelloReply{} }
func (m *HelloReply) String() string { return proto.CompactTextString(m) }
func (*HelloReply) ProtoMessage()    {}
func (*HelloReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_17b8c58d586b62f2, []int{1}
}

func (m *HelloReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloReply.Unmarshal(m, b)
}
func (m *HelloReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloReply.Marshal(b, m, deterministic)
}
func (m *HelloReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloReply.Merge(m, src)
}
func (m *HelloReply) XXX_Size() int {
	return xxx_messageInfo_HelloReply.Size(m)
}
func (m *HelloReply) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloReply.DiscardUnknown(m)
}

var xxx_messageInfo_HelloReply proto.InternalMessageInfo

func (m *HelloReply) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type ErrorDetail struct {
	Code                 ErrorCode `protobuf:"varint,1,opt,name=code,proto3,enum=helloworld.ErrorCode" json:"code,omitempty"`
	Message              string    `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ErrorDetail) Reset()         { *m = ErrorDetail{} }
func (m *ErrorDetail) String() string { return proto.CompactTextString(m) }
func (*ErrorDetail) ProtoMessage()    {}
func (*ErrorDetail) Descriptor() ([]byte, []int) {
	return fileDescriptor_17b8c58d586b62f2, []int{2}
}

func (m *ErrorDetail) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ErrorDetail.Unmarshal(m, b)
}
func (m *ErrorDetail) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ErrorDetail.Marshal(b, m, deterministic)
}
func (m *ErrorDetail) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ErrorDetail.Merge(m, src)
}
func (m *ErrorDetail) XXX_Size() int {
	return xxx_messageInfo_ErrorDetail.Size(m)
}
func (m *ErrorDetail) XXX_DiscardUnknown() {
	xxx_messageInfo_ErrorDetail.DiscardUnknown(m)
}

var xxx_messageInfo_ErrorDetail proto.InternalMessageInfo

func (m *ErrorDetail) GetCode() ErrorCode {
	if m != nil {
		return m.Code
	}
	return ErrorCode_UNKNOWN
}

func (m *ErrorDetail) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterEnum("helloworld.ErrorCode", ErrorCode_name, ErrorCode_value)
	proto.RegisterType((*HelloRequest)(nil), "helloworld.HelloRequest")
	proto.RegisterType((*HelloReply)(nil), "helloworld.HelloReply")
	proto.RegisterType((*ErrorDetail)(nil), "helloworld.ErrorDetail")
}

func init() { proto.RegisterFile("helloworld.proto", fileDescriptor_17b8c58d586b62f2) }

var fileDescriptor_17b8c58d586b62f2 = []byte{
	// 274 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x91, 0xcf, 0x4b, 0xc3, 0x30,
	0x14, 0xc7, 0xd7, 0x59, 0x57, 0xf7, 0x36, 0x34, 0x3c, 0x51, 0x8a, 0x27, 0xe9, 0x41, 0xd4, 0xc3,
	0x0e, 0xf3, 0x2e, 0x94, 0x36, 0x68, 0x51, 0xba, 0x12, 0x37, 0x7f, 0x9c, 0xa4, 0xda, 0x87, 0x0a,
	0x99, 0xa9, 0x69, 0x45, 0xfa, 0x47, 0xf8, 0x3f, 0x4b, 0xa3, 0x75, 0x11, 0xbc, 0xe5, 0x7d, 0xf2,
	0xc9, 0x97, 0xe4, 0x1b, 0x60, 0xcf, 0x24, 0xa5, 0xfa, 0x50, 0x5a, 0x16, 0x93, 0x52, 0xab, 0x5a,
	0x21, 0xac, 0x48, 0x10, 0xc0, 0xf8, 0xbc, 0x9d, 0x04, 0xbd, 0xbd, 0x53, 0x55, 0x23, 0x82, 0xfb,
	0x9a, 0x2f, 0xc9, 0x77, 0xf6, 0x9d, 0xc3, 0xa1, 0x30, 0xeb, 0xe0, 0x00, 0xe0, 0xc7, 0x29, 0x65,
	0x83, 0x3e, 0x78, 0x4b, 0xaa, 0xaa, 0xfc, 0xa9, 0x93, 0xba, 0x31, 0x10, 0x30, 0xe2, 0x5a, 0x2b,
	0x1d, 0x53, 0x9d, 0xbf, 0x48, 0x3c, 0x02, 0xf7, 0x51, 0x15, 0xdf, 0xd6, 0xe6, 0x74, 0x67, 0x62,
	0xdd, 0xc3, 0x68, 0x91, 0x2a, 0x48, 0x18, 0xc5, 0xce, 0xec, 0xff, 0xc9, 0x3c, 0xfe, 0x74, 0x60,
	0xf8, 0x6b, 0xe3, 0x08, 0xbc, 0x45, 0x7a, 0x91, 0xce, 0x6e, 0x52, 0xd6, 0xc3, 0x6d, 0xd8, 0x4a,
	0xd2, 0xeb, 0xf0, 0x32, 0x89, 0xef, 0x05, 0x8f, 0x78, 0x92, 0xcd, 0x99, 0xd3, 0x42, 0x7e, 0x9b,
	0x25, 0x82, 0xaf, 0x60, 0x1f, 0x19, 0x8c, 0x3b, 0x33, 0x0a, 0x45, 0xcc, 0xd6, 0x5a, 0xd2, 0x69,
	0x86, 0xb8, 0x76, 0x5a, 0x34, 0x5b, 0xa4, 0x73, 0x71, 0xc7, 0xd6, 0x5b, 0x2d, 0x13, 0x3c, 0x0b,
	0xbb, 0x83, 0x83, 0x69, 0x02, 0xde, 0x99, 0x26, 0xaa, 0x49, 0xe3, 0x29, 0x6c, 0x5c, 0xe5, 0x8d,
	0x69, 0x06, 0x7d, 0xfb, 0x75, 0x76, 0xa1, 0x7b, 0xbb, 0xff, 0xec, 0x94, 0xb2, 0x09, 0x7a, 0x0f,
	0x03, 0xf3, 0x1b, 0x27, 0x5f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x5f, 0x59, 0x05, 0xbb, 0xa1, 0x01,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// GreeterClient is the client API for Greeter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GreeterClient interface {
	SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error)
}

type greeterClient struct {
	cc *grpc.ClientConn
}

func NewGreeterClient(cc *grpc.ClientConn) GreeterClient {
	return &greeterClient{cc}
}

func (c *greeterClient) SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error) {
	out := new(HelloReply)
	err := c.cc.Invoke(ctx, "/helloworld.Greeter/SayHello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GreeterServer is the server API for Greeter service.
type GreeterServer interface {
	SayHello(context.Context, *HelloRequest) (*HelloReply, error)
}

// UnimplementedGreeterServer can be embedded to have forward compatible implementations.
type UnimplementedGreeterServer struct {
}

func (*UnimplementedGreeterServer) SayHello(ctx context.Context, req *HelloRequest) (*HelloReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayHello not implemented")
}

func RegisterGreeterServer(s *grpc.Server, srv GreeterServer) {
	s.RegisterService(&_Greeter_serviceDesc, srv)
}

func _Greeter_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/helloworld.Greeter/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).SayHello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Greeter_serviceDesc = grpc.ServiceDesc{
	ServiceName: "helloworld.Greeter",
	HandlerType: (*GreeterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _Greeter_SayHello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "helloworld.proto",
}
