// Code generated by protoc-gen-go. DO NOT EDIT.
// source: path

package path

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

func init() { proto.RegisterFile("path", fileDescriptor_a0af9f865bf637e6) }

var fileDescriptor_a0af9f865bf637e6 = []byte{
	// 30 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x62, 0x29, 0x48, 0x2c, 0xc9,
	0x00, 0x04, 0x00, 0x00, 0xff, 0xff, 0x16, 0x70, 0xc9, 0xcf, 0x06, 0x00, 0x00, 0x00,
}
