version: '2.4'
services:

  gateway:
    build:
      context: .
      dockerfile: Dockerfile-gateway
    networks:
      service-mesh:
        aliases:
          - gateway
    expose:
      - "3000"
    ports:
      - "3000:3000"
    environment:
      - ENDPOINT=front-proxy:8000

  gateway-sidecar: &sidecar
    build:
      context: .
      dockerfile: Dockerfile-sidecar
    container_name: front-proxy
    volumes:
      - ./gateway-sidecar.yaml:/etc/sidecar-envoy.yaml
    networks:
      - service-mesh
    expose:
      - "8000"
      - "8001"
    ports:
      - "8001:8001"

  grpc:
    build:
      context: .
      dockerfile: Dockerfile-grpc
    networks:
      service-mesh:
        aliases:
          - backend
    expose:
      - "8080"

  grpc-sidecar:
    <<: *sidecar
    volumes:
      - ./grpc-sidecar.yaml:/etc/sidecar-envoy.yaml
    ports:
      - "8002:8001"

networks:
  service-mesh: {}
