version: '2.4'
services:

  gateway:
    build:
      context: .
      dockerfile: Dockerfile-gateway
    networks:
      - front-proxy
    expose:
      - "3000"
    ports:
      - "3000:3000"
    environment:
      - ENDPOINT=front-proxy:8000

  front-envoy:
    build:
      context: .
      dockerfile: Dockerfile-frontenvoy
    container_name: front-proxy
    volumes:
      - ./front-envoy.yaml:/etc/front-envoy.yaml
    networks:
      - front-proxy
    expose:
      - "8000"
      - "8001"

  grpc1:
    build:
      context: .
      dockerfile: Dockerfile-grpc
    container_name: grpc1
    networks:
      - front-proxy
    expose:
      - "8080"
  grpc2:
    build:
      context: .
      dockerfile: Dockerfile-grpc
    container_name: grpc2
    networks:
      - front-proxy
    expose:
      - "8080"

networks:
  front-proxy: {}
